"""Make sender_id and receiver_id nullable in transactions table

Revision ID: daf6e76b351c
Revises: 
Create Date: 2025-04-27 14:43:38.642813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf6e76b351c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kyc')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint('account_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('eth_wallets', schema=None) as batch_op:
        batch_op.drop_constraint('eth_wallets_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('support_tickets_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('ticket_replies', schema=None) as batch_op:
        batch_op.alter_column('ticket_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('transactions_sender_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('transactions_receiver_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['receiver_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transactions_receiver_id_fkey', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('transactions_sender_id_fkey', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('ticket_replies', schema=None) as batch_op:
        batch_op.alter_column('ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('support_tickets_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('eth_wallets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('eth_wallets_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('account_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    op.create_table('kyc',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kyc_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('kyc_document', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('document_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('front_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('back_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_with_document_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='kyc_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='kyc_pkey'),
    sa.UniqueConstraint('user_id', name='kyc_user_id_key')
    )
    # ### end Alembic commands ###
